### PR TITLE
Show locked balance

### LINKED ISSUE #50: Show amount of locked tokens
We could display information about part of the balance that is locked. 
Need some work on the backend @tdroxler  
To be refined.

### PR DESCRIPTION
**Pull request by nop33**
Needs to be properly tested once the alephium-js package gets the updated schema: https://github.com/alephium/alephium-js/pull/34

Closes #50

### CODE REVIEW

**Comment by tdroxler** [comment]
maybe this one is a bit more complicate to have a screenshot, as you need a wallet with locked balance, but would be nice for poor backend dev like me who don't realize how it looks form the code :stuck_out_tongue_closed_eyes:

**Comment by nop33** [comment]
@tdroxler I posted some screenshots in the issue #50 !

**Comment by mvaivre** [comment]
LGTM

To be merged when the backend is fully deployed. Let's double check the API types as well, making sure that `lockedBalance` should always return a string, and can't be undefined.

**Comment by nop33** [comment]
> To be merged when the backend is fully deployed.

It would seem that the backend changes have not yet been deployed (I don't see the `lockedBalance` field in the schema: https://mainnet-backend.alephium.org/docs/index.html?url=/docs/explorer-backend-openapi.json#/Addressess/getAddressesAddress

How can I get notified when that gets deployed? @tdroxler?

**Comment by nop33** [comment]
Rebased.

**Pull request merged**
